# Generated by Django 4.2.1 on 2023-05-19 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment_available_dates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('service', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='review',
            old_name='Review',
            new_name='review',
        ),
        migrations.AddField(
            model_name='appointment',
            name='selected_date',
            field=models.DateField(default=datetime.date(2023, 5, 19)),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.CharField(default='Botox', max_length=255),
        ),
        migrations.AddField(
            model_name='review',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
